// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Students.DBCore.Contexts;

#nullable disable

namespace Students.DBCore.Migrations
{
    [DbContext(typeof(PgContext))]
    [Migration("20231208180943_ChangeRequiredFields")]
    partial class ChangeRequiredFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroupStudent", b =>
                {
                    b.Property<Guid>("GroupsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentsId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupsId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("GroupStudent");
                });

            modelBuilder.Entity("Students.Models.EducationForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EducationForms");
                });

            modelBuilder.Entity("Students.Models.EducationProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EducationFormId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EducationTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FEAProgramId")
                        .HasColumnType("uuid");

                    b.Property<int>("HoursCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCollegeProgram")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDOTProgram")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsModularProgram")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNetworkProgram")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EducationFormId");

                    b.HasIndex("EducationTypeId");

                    b.HasIndex("FEAProgramId");

                    b.ToTable("EducationPrograms");
                });

            modelBuilder.Entity("Students.Models.EducationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EducationTypes");
                });

            modelBuilder.Entity("Students.Models.FEAProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FEAPrograms");
                });

            modelBuilder.Entity("Students.Models.FinancingType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FinancingTypes");
                });

            modelBuilder.Entity("Students.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EducationProgramId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EducationProgramId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Students.Models.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Disability")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("EducationContract")
                        .HasColumnType("text");

                    b.Property<Guid>("EducationProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntranceExamination")
                        .HasColumnType("text");

                    b.Property<Guid?>("FinancingTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Interview")
                        .HasColumnType("text");

                    b.Property<string>("JobCV")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobResult")
                        .HasColumnType("text");

                    b.Property<string>("OrderOfAdmission")
                        .HasColumnType("text");

                    b.Property<string>("OrderOfExpulsion")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ScopeOfActivityLv1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScopeOfActivityLv2Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("StudentEducationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StudentStatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("EducationProgramId");

                    b.HasIndex("FinancingTypeId");

                    b.HasIndex("ScopeOfActivityLv1Id");

                    b.HasIndex("ScopeOfActivityLv2Id");

                    b.HasIndex("StudentEducationId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentStatusId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Students.Models.ScopeOfActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("NameOfScope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScopesOfActivity");
                });

            modelBuilder.Entity("Students.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentSeries")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullNameDocument")
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SNILS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Students.Models.StudentDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StudentDocuments");
                });

            modelBuilder.Entity("Students.Models.StudentEducation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StudentEducations");
                });

            modelBuilder.Entity("Students.Models.StudentStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StudentStatuses");
                });

            modelBuilder.Entity("GroupStudent", b =>
                {
                    b.HasOne("Students.Models.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Students.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Students.Models.EducationProgram", b =>
                {
                    b.HasOne("Students.Models.EducationForm", "EducationForm")
                        .WithMany()
                        .HasForeignKey("EducationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Students.Models.EducationType", "EducationType")
                        .WithMany()
                        .HasForeignKey("EducationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Students.Models.FEAProgram", "FEAProgram")
                        .WithMany()
                        .HasForeignKey("FEAProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationForm");

                    b.Navigation("EducationType");

                    b.Navigation("FEAProgram");
                });

            modelBuilder.Entity("Students.Models.Group", b =>
                {
                    b.HasOne("Students.Models.EducationProgram", "EducationProgram")
                        .WithMany()
                        .HasForeignKey("EducationProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationProgram");
                });

            modelBuilder.Entity("Students.Models.Request", b =>
                {
                    b.HasOne("Students.Models.StudentDocument", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId");

                    b.HasOne("Students.Models.EducationProgram", "EducationProgram")
                        .WithMany()
                        .HasForeignKey("EducationProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Students.Models.FinancingType", "FinancingType")
                        .WithMany()
                        .HasForeignKey("FinancingTypeId");

                    b.HasOne("Students.Models.ScopeOfActivity", "ScopeOfActivityLv1")
                        .WithMany()
                        .HasForeignKey("ScopeOfActivityLv1Id");

                    b.HasOne("Students.Models.ScopeOfActivity", "ScopeOfActivityLv2")
                        .WithMany()
                        .HasForeignKey("ScopeOfActivityLv2Id");

                    b.HasOne("Students.Models.StudentEducation", "StudentEducation")
                        .WithMany()
                        .HasForeignKey("StudentEducationId");

                    b.HasOne("Students.Models.Student", "Student")
                        .WithMany("Requests")
                        .HasForeignKey("StudentId");

                    b.HasOne("Students.Models.StudentStatus", "StudentStatus")
                        .WithMany()
                        .HasForeignKey("StudentStatusId");

                    b.Navigation("DocumentType");

                    b.Navigation("EducationProgram");

                    b.Navigation("FinancingType");

                    b.Navigation("ScopeOfActivityLv1");

                    b.Navigation("ScopeOfActivityLv2");

                    b.Navigation("Student");

                    b.Navigation("StudentEducation");

                    b.Navigation("StudentStatus");
                });

            modelBuilder.Entity("Students.Models.Student", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
